import type { DomElementTagNameMap } from "./types";

export const UNITLESS_CSS_PROPS: Record<string, 1> = {
  opacity: 1,
  zIndex: 1,
  fontWeight: 1,
  lineHeight: 1,
  flexGrow: 1,
  flexShrink: 1,
  order: 1,
  zoom: 1,
  scale: 1,
  counterIncrement: 1,
  counterReset: 1,
  tabSize: 1,
  orphans: 1,
  widows: 1,
  columns: 1,
  columnCount: 1,
  gridRow: 1,
  gridColumn: 1,
};

export const VENDOR_CSS_PROPS: Record<string, 1> = {
  WebkitAppearance: 1,
};

export const SVG_TAGS = [
  "svgA", // alias for <a>
  "svgStyle", // alias for <style>
  "svg",
  "animate",
  "animateMotion",
  "animateTransform",
  "circle",
  "clipPath",
  "defs",
  "desc",
  "ellipse",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feDistantLight",
  "feDropShadow",
  "feFlood",
  "feFuncA",
  "feFuncB",
  "feFuncG",
  "feFuncR",
  "feGaussianBlur",
  "feImage",
  "feMerge",
  "feMergeNode",
  "feMorphology",
  "feOffset",
  "fePointLight",
  "feSpecularLighting",
  "feSpotLight",
  "feTile",
  "feTurbulence",
  "filter",
  "foreignObject",
  "g",
  "image",
  "line",
  "linearGradient",
  "marker",
  "mask",
  "metadata",
  "mpath",
  "path",
  "pattern",
  "polygon",
  "polyline",
  "radialGradient",
  "rect",
  "script",
  "set",
  "stop",
  "switch",
  "symbol",
  "text",
  "textPath",
  "title",
  "tspan",
  "use",
  "view",
];

export const TAG_ALIAS = {
  svgA: "a",
  svgStyle: "style",
} satisfies Record<string, keyof DomElementTagNameMap>;

export type TagAlias = typeof TAG_ALIAS;
